spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-management
    username: root
    password: krish@123
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 733976610069-iira4kt4dol6sggq44eia63tpg8ncsqt.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
           
           
           
           
           
           
           
           
           
           
           
           
           